services:
  ss-rust:
    image: lockp111/ssserver-rust:1.0.0
    # image: lockp111/sslocal-rust:1.0.0
    container_name: ss-rust
    volumes:
      - ./server.json:/etc/shadowsocks-rust/config.json
      # - ./client.json:/etc/shadowsocks-rust/config.json
    ports:
      # - "465:465"
      - "3000:3000"
      - "3000:3000/udp"
    restart: always
    logging:
      options:
        max-size: "1g"
